services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: spd_orm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./orm/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
  spring-orm:
    build:
      context: ./orm
      dockerfile: Dockerfile
    container_name: spring-orm-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spd_orm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: America/Sao_Paulo
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data: