spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: api-administrativa
              uri: http://spring-orm:8081
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0

            - id: api-publica
              uri: http://spring-odm:8082
              predicates:
                  - Path=/public/**
              filters:
                  - StripPrefix=1
  application:
    name: api-gateway