spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: api-administrativa
              uri: ${SPRING_ORM_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0

            - id: api-publica
              uri: ${SPRING_ODM_SERVICE_URL:http://localhost:8082}
              predicates:
                  - Path=/public/**
              filters:
                  - StripPrefix=0
  application:
    name: api-gateway