spring:
  application:
    name: orm
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spd_orm
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Configurações do SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    # Configurações adicionais para funcionar com JWT
    csrf:
      enabled: false
    disable-swagger-default-url: true
    display-request-duration: true
    # Configurar o contexto path para o Swagger
  show-actuator: false

server:
  port: 8081
  servlet:
    context-path: /api