spring:
  application:
    name: orm
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spd_orm
    username: postgres
    password: postgres

# Configurações do SpringDoc OpenAPI (Swagger)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

server:
  servlet:
    context-path: /api
  port: 8080