spring:
  application:
    name: odm
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: spd_odm
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

server:
  servlet:
    context-path: /public
  port: 8082

# SpringDoc OpenAPI (Swagger) Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
